### ISSUE TITLE
Incorrect lifetime units for certain particles

### ISSUE THREAD

**Issue by mjkramer** [particledatagroup/api#15]
For a number of particles (including at least the B0, B+/-, B_s, Xi_b, and Lambda_b), the `lifetime` property gives a value that is not in the required units (namely, seconds). For example, `api.get_particle_by_name('B0').lifetime` returns `1517.0` instead of `1.517e-12`. This behavior has been tracked down to a parsing/encoding issue in the database, specifically for some of the summary table values that have a `value_type` of `'V'` ("OUR EVALUATION"). We are currently working on a fix, which will be included in a patch release ASAP.

**Comment by juergberinger** [comment]
Fixed in version 0.1.3, see #18
