### ISSUE TITLE
Remove `distutils` from `setup.py`

### ISSUE THREAD

**Issue by redeboer** [particledatagroup/api#17]
Thank you for developing this API package, I am following the developments with interest!

I tried to install the `pdg` package in Python 3.12, but get

```
ModuleNotFoundError: No module named 'distutils.command.register'
```

The reason seems to be that `setup.py` is using [`distutils`](https://docs.python.org/3.11/library/distutils.html) has been been removed since Python 3.12:

https://github.com/particledatagroup/api/blob/ed22911000696953436ca27b32f90efeef633d7c/setup.py#L4C6-L11

This is a problem for lower versions of Python in other package managers as well, specifically when using [`uv`](https://docs.astral.sh/uv/).

It seems that the part that requires `distutils` is meant publishing the package on PyPI. This should not be exposed to the installation process. Better would be [to use `twine`](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/) or [to publish through GitHub CI](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/).

**Comment by juergberinger** [comment]
Thanks a lot for spotting this! We switched to twine already a while ago and the code related to distutils wasn't removed by accident. Fixed in version 0.1.3, see #18.
